### ISSUE TITLE
v1.2 questions/review

### ISSUE THREAD

**Issue by puzrin** [Jan--Henrik/OtterPill#6]
1. U1
   - Seems pin5 should not be connected to 3.3v.
   - Also, you may wish to consider [PESDALC10N5VU](https://lcsc.com/product-detail/Diodes-ESD_PESDALC10N5VU_C169334.html) for better routability.
2. If you care about ESD protecion, VBUS needs TVS. For example [SJD12A22L01](https://lcsc.com/product-detail/New-Arrivals_Brightking-Elec-TAIWAN-SJD12A22L01_C313187.html)
3. U4
   - it's not clear why R8,R9 may be needed
   - i don't know why not used on your schematic, but in datasheet FUSB302B has 11 & 14 pins used (for pull-down), those must be connected to CC0/CC1 in dead battery mode.
   - R1/R2 - not clear why, if you need dead battery mode only.
4. U3
   - (not tested myself) [TPS62177DQCR](https://lcsc.com/product-detail/DC-DC-Converters_Texas-Instruments_TPS62177DQCR_Texas-Instruments-Texas-Instruments-TPS62177DQCR_C91241.html) needs 3 components less. Disadvantage - wish 4.75V to start.
5. R13 - not needed IMO.
6. It would be nice to see this project on EasyEDA, to be able order PCB, SMT stencil & components at once in couple of clicks.
   - For SMT stencil positioning, i would add two 0.7mm holes to PCB & paste layer. Then use 22 AWG wire to pin both to silicon pad.

---

I'm closing this, since this is not a bug report. Only my notes, which can be safely ignored :)

**Comment by Jana-Marie** [comment]
Hey, Thanks for the input!

1.
 - Pin 5 needs to be connected to 3.3V to clamp voltage spikes to 3.3V. This pin is usually connected to VBUS (5V), this is however not possible since this board does not have a 5V rail.
 - I didn't have a problem routing the USBLC, but thanks for the recommendation!
 - note: I will replace the USBLC with ESDU5V0H4, which is cheaper and also features a TVS Diode for the 3.3V rail.
2.
 - noted, this will be added to todo!
3.
 - R8, R9 are indeed not needed!
 - They are connected to CC0/CC1, the symbol is unclear and confusing.
 - R1 and R2 can be populated, if no PD capability is needed. This saves another ~0.70€
4.
 -  TPS62177DQCR is almost four times the price!
5.
 - R13 prevents a direct short through PC13
6.
 - I really wish for a non EasyEDA direct ordering function for JLCSMT! Currently I am not planning on serving the files via EasyEDA, however all files for direct ordering are present within this repository. Please have a look at the [production folder.](https://github.com/Jan--Henrik/OtterPill/tree/master/HW%20v1.2/production)
 - This project is not intended for manual assembly, it is, at the same price as a stencil ($7), almost 100% JLCSMT compatible.

**Comment by Jana-Marie** [comment]
https://github.com/Jan--Henrik/OtterPill/blob/master/README.md#todo-for-hw-v13

**Comment by puzrin** [comment]
1.

> Pin 5 needs to be connected to 3.3V to clamp voltage spikes to 3.3V. This pin is usually connected to VBUS (5V), this is however not possible since this board does not have a 5V rail.

IMO clamping of ESD is done by inner TVS. Limiting via MCU power line can be done only for weak signals, not this case. If you see USB-C modules, they have no pin for power line at all.

USBLC has power pin, because it's for 5v of USB 2.0 VBUS. Not for MCU power line.


5.

> R13 prevents a direct short through PC13

How can this happen? Firmware mistake? Pins are input by default after reset.

6.

I did not suggesed to drop existing distribuion methods. Only suggested to add one more for "noobs", from own experience. See [example](https://github.com/speedcontrols/ac_sc_grinder/blob/v2doc/doc/assembly.md). It's focused on goal "everybody should be able to assemble that at home". 

I see no principal problems with manual assembly of your board. I would only add vias under MCU & FUSB, to simplify soldering without paste. [Here](https://easyeda.com/puzrin/solder-training-board) is example what i mean.
